
export const SideBarData = [{
  title:"UseState",
  link:"/usestate"
},{
    title:"UseReducer",
    link:'/usereducer'
},{
    title:"UseRef",
    link:"/useref"
},{
    title:"UseEffect",
    link:"/useeffect"
},{
    title:"UseId",
    link:"/useid"
},{
    title:"UseContext",
    link:"/usecontext"
},{
    title:"UseCallback",
    link:"/usecallback"
},{
    title:"UseDebugValue",
    link:"/usedebugvalue"
},,{
    title:"UseLayoutEffect",
    link:"/uselayouteffect"
},{
    title:"UseMemo",
    link:"/usememo"
}]